"""Count how many CUAD contracts have a labeled clause in each of the 41 categories.

    python manage.py count_categories

Change Notice 1: "Count the positives per category before you commit." The table is printed and
saved to docs/cuad-category-counts.md, so the numbers behind the category choice can be checked
later. Categories already in seed/playbook.csv are marked.
"""
import csv

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from core.cuad import CUAD_JSON, category_summary

PLAYBOOK = settings.BASE_DIR / "seed" / "playbook.csv"
REPORT = settings.BASE_DIR / "docs" / "cuad-category-counts.md"
CHECK_SET_SIZE = 30  # the brief's minimum check set (section 6.1)


class Command(BaseCommand):
    help = "Count labeled clauses per CUAD category and save the table to docs/cuad-category-counts.md."

    def handle(self, *args, **options):
        if not CUAD_JSON.exists():
            raise CommandError(f"CUAD is not downloaded. Expected {CUAD_JSON}")
        contract_count, summary = category_summary()
        in_playbook = set()
        if PLAYBOOK.exists():
            with PLAYBOOK.open(newline="") as f:
                in_playbook = {row["cuad_category"].strip() for row in csv.DictReader(f)}

        lines = [
            "# CUAD category counts",
            "",
            f"Generated by `python manage.py count_categories` from CUAD v1 ({contract_count} contracts).",
            "",
            "- **Contracts**: how many contracts have at least one labeled clause in the category.",
            f"- **In {CHECK_SET_SIZE} contracts**: how many of those to expect in a check set of {CHECK_SET_SIZE} contracts "
            "picked at random. Too few, and recall for that category cannot be measured.",
            "- **Clauses**: the total number of labeled clauses.",
            "- **Playbook**: ✓ if the category is in seed/playbook.csv.",
            "",
            f"| Category | Contracts | Share | In {CHECK_SET_SIZE} contracts | Clauses | Playbook | CUAD description |",
            "|---|---|---|---|---|---|---|",
        ]
        for category, (contracts, clauses, description) in sorted(summary.items(), key=lambda item: -item[1][0]):
            share = contracts / contract_count
            mark = "✓" if category in in_playbook else ""
            lines.append(
                f"| {category} | {contracts} | {share:.0%} | {share * CHECK_SET_SIZE:.1f} | {clauses} | {mark} "
                f"| {description.replace('|', '/')} |"
            )
            self.stdout.write(
                f"{contracts:>4} contracts {share:>4.0%}  ~{share * CHECK_SET_SIZE:>4.1f} in {CHECK_SET_SIZE}  "
                f"{clauses:>5} clauses  {'*' if mark else ' '} {category}"
            )
        REPORT.write_text("\n".join(lines) + "\n")
        self.stdout.write(f"\nSaved {REPORT.relative_to(settings.BASE_DIR)}. * = in seed/playbook.csv")
        for category in sorted(in_playbook - set(summary)):
            self.stdout.write(self.style.WARNING(f"{category!r} in the playbook is not a CUAD category."))
