# Generated by Django 6.1.1 on 2026-09-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='default_severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Reading document'), ('read_failed', 'Could not read document'), ('awaiting_id', 'Waiting for identification'), ('in_review', 'In review'), ('cleared', 'Cleared'), ('cleared_conditions', 'Cleared with conditions'), ('escalated', 'Escalated')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='flag',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='kind',
            field=models.CharField(choices=[('present', 'Provision found'), ('deviation', 'Deviation'), ('gap', 'Gap')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='flag',
            name='source',
            field=models.CharField(choices=[('rule', 'Text rule'), ('ai', 'AI model'), ('manual', 'Marked by a person')], max_length=10),
        ),
        migrations.AlterField(
            model_name='provision',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='flag_confidence_between_0_and_1'),
        ),
    ]
