# Generated by Django 6.1.1 on 2026-09-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provision_default_severity_alter_agreement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='read_error',
            field=models.TextField(blank=True),
        ),
    ]
