# Generated by Django 6.1.1 on 2026-09-14 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agreement_read_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flags_marked', to=settings.AUTH_USER_MODEL),
        ),
    ]
