# Generated by Django 6.1.1 on 2026-09-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flag_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='method',
            field=models.CharField(choices=[('rules', 'Text rule'), ('ai', 'AI model')], default='ai', max_length=10),
        ),
    ]
