# Generated by Django 6.1.1 on 2026-09-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_provision_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='source',
            field=models.CharField(choices=[('rule', 'Text rule'), ('keyword', 'Playbook keyword'), ('ai', 'AI model'), ('manual', 'Marked by a person')], max_length=10),
        ),
    ]
