# Generated by Django 6.1.1 on 2026-09-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuration_agreement_document_removed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provision',
            name='agreement_types',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
