"""
Django settings for the Calder agreement review project.

Generated by 'django-admin startproject' using Django 6.1.1, then edited.
Full list of settings: https://docs.djangoproject.com/en/6.1/ref/settings/
Every value that differs between a laptop and the deployed site comes from an environment
variable; docs/deployment-runbook.md lists them.
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Secrets and deployment switches come from environment variables, so no real key
# is ever saved in the repository (brief, section 9). The fallbacks below are only
# good enough for running the app on your own laptop.
DEV_SECRET_KEY = 'dev-only-not-a-secret'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', DEV_SECRET_KEY)

# Debug pages show the app's internals, so they are on only when DJANGO_DEBUG is "1".
# It defaults to on for your laptop. The deployed site sets it to "0".
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

if not DEBUG and SECRET_KEY == DEV_SECRET_KEY:
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY before running with DEBUG off.')

# The web addresses this app answers to, separated by commas. On Railway, the public
# address of the deployed site arrives in RAILWAY_PUBLIC_DOMAIN and is added here.
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
    ALLOWED_HOSTS.append(os.environ['RAILWAY_PUBLIC_DOMAIN'])

# Forms may be posted from these https addresses (Django's CSRF check compares the full origin).
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if host not in ('localhost', '127.0.0.1')]

# Railway's proxy handles HTTPS and tells Django so in this header. On the deployed site,
# the login and form cookies are only ever sent over HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

# Use our own user table (core/models.py) so every user can have a role.
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves the admin screens' CSS and JavaScript when deployed
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# A SQLite file on a laptop. On Railway, DATABASE_URL points at the Postgres database.

DATABASES = {
    'default': dj_database_url.config(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}', conn_max_age=600),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Calder is a US company, so pages show Eastern time. The database still stores UTC.
TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, images) and uploaded files

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # "collectstatic" gathers the files here, and WhiteNoise serves them
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Uploaded files (the contract PDFs). On Railway they are kept on a volume, set by MEDIA_ROOT.
# They are never served directly; core/views.py checks permission before sending one.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

# Largest contract file the intake form accepts.
MAX_UPLOAD_MB = 20

# Automatic identification to run after a document is read, separated by commas: "rules" runs the text
# rules in core/rules.py, "ai" runs the AI step in core/ai_identify.py. Each playbook provision says which
# of the two looks for it. Set AUTO_IDENTIFY to an empty value to leave identification to people.
AUTO_IDENTIFY = [method for method in os.environ.get('AUTO_IDENTIFY', 'rules,ai').split(',') if method]

# The AI step. The Anthropic library reads the key from ANTHROPIC_API_KEY; it is never stored here.
AI_MODEL = os.environ.get('AI_MODEL', 'claude-haiku-4-5')
# AI findings below this confidence are marked "low confidence" and listed last on the review page.
# A person still decides on them. (Ambiguity log question 4; the threshold note.)
# 0.9 was chosen on 2026-09-17 from the check-set run: below 0.9, three of four flags were wrong;
# at 0.9 and above, one in eleven.
AI_LOW_CONFIDENCE = float(os.environ.get('AI_LOW_CONFIDENCE', '0.9'))


# Logging in and out
# Where people go to log in, and where they land afterwards.

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'  # home sends staff to the work queue and requesters to their submissions
LOGOUT_REDIRECT_URL = 'home'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
